# Generated by Django 2.2.8 on 2021-08-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('yop', models.IntegerField()),
                ('degree', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
            ],
        ),
    ]
