# Generated by Django 2.2.8 on 2021-08-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.TextField(max_length=191)),
                ('empid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('doj', models.DateField()),
                ('dor', models.DateField()),
                ('lws', models.CharField(max_length=20)),
            ],
        ),
    ]
